# Generated by Django 4.2.9 on 2024-01-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
