# Generated by Django 4.2.9 on 2024-01-12 10:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(max_length=200)),
                ('headshot', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('background', models.TextField()),
                ('motivation', models.TextField()),
                ('fav_place', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
