# Generated by Django 4.2.9 on 2024-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_contributor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='fav_place',
            field=models.CharField(default='Favourite place in Sardinia: ', max_length=200),
        ),
    ]
