# Generated by Django 4.2.9 on 2024-01-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_contributor_fav_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='fav_place',
            field=models.CharField(max_length=200),
        ),
    ]
